security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
      dbal_provider:
        id: AdnanMula\Cards\Infrastructure\Persistence\Repository\Shared\DbalUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: dbal_provider
            form_login:
              login_path: login
              check_path: login
            logout:
              path: logout

    access_control:
         - { path: ^/keyforge/games/add, roles: ROLE_KEYFORGE }
         - { path: ^/keyforge/decks/import, roles: ROLE_KEYFORGE }
         - { path: ^/gwent, roles: ROLE_GWENT }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
