security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
      dbal_provider:
        id: AdnanMula\Cards\Infrastructure\Persistence\Repository\Shared\DbalUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: dbal_provider
            access_denied_handler: AdnanMula\Cards\Infrastructure\Security\AccessDeniedHandler
            form_login:
              login_path: login
              check_path: login
            logout:
              path: logout

    access_control:
         - { path: ^/games/new, roles: ROLE_KEYFORGE }
         - { path: ^/decks/import, roles: ROLE_KEYFORGE }
         - { path: ^/competitions, roles: ROLE_KEYFORGE }
         - { path: ^/users, roles: ROLE_KEYFORGE }
         - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: ROLE_KEYFORGE
        ROLE_KEYFORGE: ROLE_BASIC

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
