version: '3.4'
services:
  php-fpm:
    build:
      context: docker/php
    container_name: cards_php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ~/.composer:/.composer
    networks:
      - network_cards
  nginx:
    container_name: cards_nginx
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
      target: basic
    working_dir: /var/www/html
    volumes:
      - ./public:/var/www/html
      - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
    ports:
      - ${API_PORT}:80
    networks:
      - network_cards
  adminer:
    image: adminer:latest
    container_name: cards_adminer
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - network_cards
  postgres:
    image: postgres:11.1-alpine
    container_name: cards_postgres
    ports:
      - 127.0.0.1:${DATABASE_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - network_cards

networks:
  network_cards:
    driver: bridge
