services:
  AdnanMula\Cards\Domain\Model\Keyforge\Deck\KeyforgeDeckRepository:
    alias: AdnanMula\Cards\Infrastructure\Persistence\Repository\Keyforge\Deck\KeyforgeDeckDbalRepository
  AdnanMula\Cards\Domain\Model\Keyforge\Deck\KeyforgeDeckUserDataRepository:
    alias: AdnanMula\Cards\Infrastructure\Persistence\Repository\Keyforge\Deck\KeyforgeDeckUserDataDbalRepository
  AdnanMula\Cards\Domain\Model\Keyforge\Deck\KeyforgeDeckStatHistoryRepository:
    alias: AdnanMula\Cards\Infrastructure\Persistence\Repository\Keyforge\Deck\KeyforgeDeckStatHistoryDbalRepository
  AdnanMula\Cards\Domain\Model\Keyforge\Game\KeyforgeGameRepository:
    alias: AdnanMula\Cards\Infrastructure\Persistence\Repository\Keyforge\Game\KeyforgeGameDbalRepository
  AdnanMula\Cards\Domain\Model\Keyforge\User\KeyforgeUserRepository:
    alias: AdnanMula\Cards\Infrastructure\Persistence\Repository\Keyforge\User\KeyforgeUserDbalRepository
  AdnanMula\Cards\Domain\Model\Keyforge\Game\KeyforgeCompetitionRepository:
    alias: AdnanMula\Cards\Infrastructure\Persistence\Repository\Keyforge\Game\KeyforgeCompetitionDbalRepository
  AdnanMula\Cards\Domain\Model\Keyforge\Deck\KeyforgeTagRepository:
    alias: AdnanMula\Cards\Infrastructure\Persistence\Repository\Keyforge\Deck\KeyforgeTagDbalRepository
  AdnanMula\Cards\Domain\Model\Keyforge\Card\KeyforgeCardRepository:
    alias: AdnanMula\Cards\Infrastructure\Persistence\Repository\Keyforge\Card\KeyforgeCardDbalRepository
  AdnanMula\Cards\Domain\Model\Keyforge\Stat\KeyforgeStatRepository:
    alias: AdnanMula\Cards\Infrastructure\Persistence\Repository\Keyforge\Stat\KeyforgeStatDbalRepository