services:
  AdnanMula\Cards\Domain\Model\Keyforge\KeyforgeDeckRepository:
    alias: AdnanMula\Cards\Infrastructure\Persistence\Repository\Keyforge\KeyforgeDeckDbalRepository
  AdnanMula\Cards\Domain\Model\Keyforge\KeyforgeDeckStatHistoryRepository:
    alias: AdnanMula\Cards\Infrastructure\Persistence\Repository\Keyforge\KeyforgeDeckStatHistoryDbalRepository
  AdnanMula\Cards\Domain\Model\Keyforge\KeyforgeGameRepository:
    alias: AdnanMula\Cards\Infrastructure\Persistence\Repository\Keyforge\KeyforgeGameDbalRepository
  AdnanMula\Cards\Domain\Model\Keyforge\KeyforgeUserRepository:
    alias: AdnanMula\Cards\Infrastructure\Persistence\Repository\Keyforge\KeyforgeUserDbalRepository
  AdnanMula\Cards\Domain\Model\Keyforge\KeyforgeCompetitionRepository:
    alias: AdnanMula\Cards\Infrastructure\Persistence\Repository\Keyforge\KeyforgeCompetitionDbalRepository
  AdnanMula\Cards\Domain\Model\Keyforge\KeyforgeTagRepository:
    alias: AdnanMula\Cards\Infrastructure\Persistence\Repository\Keyforge\KeyforgeTagDbalRepository