keyforge_home:
  path: /
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Stats\GeneralStatsController
  methods: [GET]

keyforge_user_list:
  path: /users
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\User\ListUsersController
  methods: [GET]

keyforge_decks:
  path: /decks
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Stats\Deck\ListDecksController
  methods: [GET]

keyforge_my_decks:
  path: /my-decks
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Stats\Deck\MyDecksController
  methods: [GET]

keyforge_ownership_update:
  path: /ownership/{id}
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Deck\UpdateOwnership\UpdateDeckOwnershipController
  methods: [ POST,DELETE ]

keyforge_deck_update_notes:
  path: /deck/notes
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Deck\UpdateNotes\UpdateDeckNotesController
  methods: [POST]

keyforge_decks_json:
  path: /decks/json
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Stats\Deck\GetDecksController
  methods: [GET]

keyforge_games_json:
  path: /games/json
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Game\List\GetGamesController
  methods: [GET]

keyforge_wiki:
  path: /wiki
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Wiki\WikiController
  methods: [GET]

keyforge_user_detail:
  path: /user/{userId}
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\User\UserDetailController
  methods: [GET]

keyforge_deck_detail:
  path: /deck/{deckId}
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Deck\Detail\DeckDetailController
  methods: [GET]

keyforge_deck_import:
  path: /decks/import
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Deck\Import\ImportDeckController
  methods: [GET,POST]

keyforge_game_create:
  path: /games/new
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Game\Create\CreateGameController
  methods: [GET,POST]

keyforge_competition_list:
  path: /competitions
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Competition\ListCompetitionsController
  methods: [GET,POST]

keyforge_competitions_json:
  path: /competitions/json
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Competition\GetCompetitionsController
  methods: [GET]

keyforge_competition_create:
  path: /competitions/new
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Competition\CreateCompetitionController
  methods: [GET,POST]

keyforge_competition_start:
  path: /competition/start
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Competition\CompetitionStartController
  methods: [POST]

keyforge_competition_game_finish:
  path: /competition/finish
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Competition\CompetitionFinishController
  methods: [POST]

keyforge_competition_view:
  path: /competitions/{reference}
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Competition\CompetitionDetailController
  methods: [GET,POST]

keyforge_competition_game_create:
  path: /competition/{fixtureId}/game/new
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Competition\CreateCompetitionGameController
  methods: [POST]

keyforge_alliance_generate:
  path: /alliance/gen
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Deck\Alliance\GenerateAlliancesController
  methods: [GET,POST]

keyforge_create_tag:
  path: /tag
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Tag\CreateTagController
  methods: [POST]

keyforge_assign_tag:
  path: /tag
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Tag\AssignTagController
  methods: [PUT]

keyforge_remove_tag:
  path: /tag
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Tag\RemoveTagController
  methods: [DELETE]

keyforge_game_analyze:
  path: /game/analyze
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Game\Detail\GameAnalyzeController
  methods: [GET, POST]

keyforge_game_detail:
  path: /game/{id}
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Game\Detail\GameDetailController
  methods: [GET]
