keyforge_home:
  path: /
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Stats\GeneralStatsController
  methods: [GET]

keyforge_user_list:
  path: /users
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Stats\User\ListUsersController
  methods: [GET]

keyforge_decks:
  path: /decks
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Stats\Deck\ListDecksController
  methods: [GET]

keyforge_my_decks:
  path: /my-decks
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Stats\Deck\MyDecksController
  methods: [GET]

keyforge_deck_claim:
  path: /deck/claim
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Deck\ClaimController
  methods: [POST]

keyforge_deck_update_notes:
  path: /deck/notes
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Deck\UpdateNotes\UpdateDeckNotesController
  methods: [POST]

keyforge_decks_json:
  path: /decks/json
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Stats\Deck\GetDecksController
  methods: [GET]

keyforge_games_json:
  path: /games/json
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Stats\Game\GetGamesController
  methods: [GET]

keyforge_wiki:
  path: /wiki
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Wiki\WikiController
  methods: [GET]

keyforge_game_list_by_user:
  path: /user/{userId}
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Stats\Game\ListGamesByUserController
  methods: [GET]

keyforge_game_list_by_deck:
  path: /deck/{deckId}
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Stats\Game\ListGamesByDeckController
  methods: [GET]

keyforge_deck_import:
  path: /decks/import
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Deck\ImportDeckController
  methods: [GET,POST]

keyforge_deck_analyze:
  path: /decks/analyze
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Deck\Analyze\AnalyzeDeckController
  methods: [GET,POST]

keyforge_game_create:
  path: /games/add
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Game\CreateGameController
  methods: [GET,POST]

keyforge_game_chain_calculator:
  path: /games/chains
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Game\ChainsCalculatorController
  methods: [GET]

keyforge_competition_list:
  path: /competitions
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Competition\ListCompetitionsController
  methods: [GET,POST]

keyforge_competitions_json:
  path: /competitions/json
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Competition\GetCompetitionsController
  methods: [GET]

keyforge_competition_create:
  path: /competitions/new
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Competition\CreateCompetitionController
  methods: [GET,POST]

keyforge_competition_start:
  path: /competition/start
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Competition\CompetitionStartController
  methods: [POST]

keyforge_competition_game_finish:
  path: /competition/finish
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Competition\CompetitionFinishController
  methods: [POST]

keyforge_competition_view:
  path: /competitions/{reference}
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Competition\CompetitionDetailController
  methods: [GET,POST]

keyforge_competition_game_create:
  path: /competition/{fixtureId}/game/new
  controller: AdnanMula\Cards\Entrypoint\Controller\Keyforge\Competition\CreateCompetitionGameController
  methods: [POST]
