services:
  middleware.dbal.transactional:
    class: AdnanMula\Cards\Infrastructure\Messaging\Dbal\DbalTransactionalMiddleware
    arguments:
      - '@repository.dbal.connection'
  middleware.exception.catcher:
    class: AdnanMula\Cards\Infrastructure\Messaging\Dbal\HandlerExceptionCatcherMiddleware
