services:
  monolog.processor.web:
    class: Monolog\Processor\WebProcessor
    tags:
      - { name: monolog.processor }

  monolog.processor.load:
    class: Monolog\Processor\LoadAverageProcessor
    tags:
      - { name: monolog.processor }

  monolog.processor.memory:
    class: Monolog\Processor\MemoryUsageProcessor
    tags:
      - { name: monolog.processor }

  monolog.processor.memory_peak:
    class: Monolog\Processor\MemoryPeakUsageProcessor
    tags:
      - { name: monolog.processor }
