<?php declare(strict_types=1);

namespace AdnanMula\Cards\Entrypoint\Controller\Keyforge\Wiki;

use AdnanMula\Cards\Domain\Model\Keyforge\Deck\ValueObject\KeyforgeHouse;
use AdnanMula\Cards\Domain\Model\Keyforge\Deck\ValueObject\KeyforgeSet;
use AdnanMula\Cards\Entrypoint\Controller\Shared\Controller;
use Symfony\Component\HttpFoundation\Response;

final class WikiController extends Controller
{
    public function __invoke(): Response
    {
        $housesPerSet = [
            KeyforgeSet::CotA->value => [
                KeyforgeHouse::BROBNAR->value => true,
                KeyforgeHouse::DIS->value => true,
                KeyforgeHouse::LOGOS->value => true,
                KeyforgeHouse::MARS->value => true,
                KeyforgeHouse::SANCTUM->value => true,
                KeyforgeHouse::REDEMPTION->value => false,
                KeyforgeHouse::SAURIAN->value => false,
                KeyforgeHouse::SHADOWS->value => true,
                KeyforgeHouse::STAR_ALLIANCE->value => false,
                KeyforgeHouse::UNFATHOMABLE->value => false,
                KeyforgeHouse::UNTAMED->value => true,
                KeyforgeHouse::EKWIDON->value => false,
                KeyforgeHouse::GEISTOID->value => false,
                KeyforgeHouse::SKYBORN->value => false,
            ],
            KeyforgeSet::AoA->value => [
                KeyforgeHouse::BROBNAR->value => true,
                KeyforgeHouse::DIS->value => true,
                KeyforgeHouse::LOGOS->value => true,
                KeyforgeHouse::MARS->value => true,
                KeyforgeHouse::SANCTUM->value => true,
                KeyforgeHouse::REDEMPTION->value => false,
                KeyforgeHouse::SAURIAN->value => false,
                KeyforgeHouse::SHADOWS->value => true,
                KeyforgeHouse::STAR_ALLIANCE->value => false,
                KeyforgeHouse::UNFATHOMABLE->value => false,
                KeyforgeHouse::UNTAMED->value => true,
                KeyforgeHouse::EKWIDON->value => false,
                KeyforgeHouse::GEISTOID->value => false,
                KeyforgeHouse::SKYBORN->value => false,
            ],
            KeyforgeSet::WC->value => [
                KeyforgeHouse::BROBNAR->value => true,
                KeyforgeHouse::DIS->value => true,
                KeyforgeHouse::LOGOS->value => true,
                KeyforgeHouse::MARS->value => false,
                KeyforgeHouse::SANCTUM->value => false,
                KeyforgeHouse::REDEMPTION->value => false,
                KeyforgeHouse::SAURIAN->value => true,
                KeyforgeHouse::SHADOWS->value => true,
                KeyforgeHouse::STAR_ALLIANCE->value => true,
                KeyforgeHouse::UNFATHOMABLE->value => false,
                KeyforgeHouse::UNTAMED->value => true,
                KeyforgeHouse::EKWIDON->value => false,
                KeyforgeHouse::GEISTOID->value => false,
                KeyforgeHouse::SKYBORN->value => false,
            ],
            KeyforgeSet::MM->value => [
                KeyforgeHouse::BROBNAR->value => false,
                KeyforgeHouse::DIS->value => true,
                KeyforgeHouse::LOGOS->value => true,
                KeyforgeHouse::MARS->value => false,
                KeyforgeHouse::SANCTUM->value => true,
                KeyforgeHouse::REDEMPTION->value => false,
                KeyforgeHouse::SAURIAN->value => true,
                KeyforgeHouse::SHADOWS->value => true,
                KeyforgeHouse::STAR_ALLIANCE->value => true,
                KeyforgeHouse::UNFATHOMABLE->value => false,
                KeyforgeHouse::UNTAMED->value => true,
                KeyforgeHouse::EKWIDON->value => false,
                KeyforgeHouse::GEISTOID->value => false,
                KeyforgeHouse::SKYBORN->value => false,
            ],
            KeyforgeSet::DT->value => [
                KeyforgeHouse::BROBNAR->value => false,
                KeyforgeHouse::DIS->value => false,
                KeyforgeHouse::LOGOS->value => true,
                KeyforgeHouse::MARS->value => false,
                KeyforgeHouse::SANCTUM->value => true,
                KeyforgeHouse::REDEMPTION->value => false,
                KeyforgeHouse::SAURIAN->value => true,
                KeyforgeHouse::SHADOWS->value => true,
                KeyforgeHouse::STAR_ALLIANCE->value => true,
                KeyforgeHouse::UNFATHOMABLE->value => true,
                KeyforgeHouse::UNTAMED->value => true,
                KeyforgeHouse::EKWIDON->value => false,
                KeyforgeHouse::GEISTOID->value => false,
                KeyforgeHouse::SKYBORN->value => false,
            ],
            KeyforgeSet::WoE->value => [
                KeyforgeHouse::BROBNAR->value => true,
                KeyforgeHouse::DIS->value => false,
                KeyforgeHouse::LOGOS->value => false,
                KeyforgeHouse::MARS->value => true,
                KeyforgeHouse::SANCTUM->value => true,
                KeyforgeHouse::REDEMPTION->value => false,
                KeyforgeHouse::SAURIAN->value => true,
                KeyforgeHouse::SHADOWS->value => false,
                KeyforgeHouse::STAR_ALLIANCE->value => true,
                KeyforgeHouse::UNFATHOMABLE->value => true,
                KeyforgeHouse::UNTAMED->value => false,
                KeyforgeHouse::EKWIDON->value => true,
                KeyforgeHouse::GEISTOID->value => false,
                KeyforgeHouse::SKYBORN->value => false,
            ],
            KeyforgeSet::GR->value => [
                KeyforgeHouse::BROBNAR->value => true,
                KeyforgeHouse::DIS->value => false,
                KeyforgeHouse::LOGOS->value => false,
                KeyforgeHouse::MARS->value => true,
                KeyforgeHouse::SANCTUM->value => false,
                KeyforgeHouse::REDEMPTION->value => false,
                KeyforgeHouse::SAURIAN->value => false,
                KeyforgeHouse::SHADOWS->value => false,
                KeyforgeHouse::STAR_ALLIANCE->value => true,
                KeyforgeHouse::UNFATHOMABLE->value => true,
                KeyforgeHouse::UNTAMED->value => true,
                KeyforgeHouse::EKWIDON->value => true,
                KeyforgeHouse::GEISTOID->value => true,
                KeyforgeHouse::SKYBORN->value => false,
            ],
            KeyforgeSet::AS->value => [
                KeyforgeHouse::BROBNAR->value => true,
                KeyforgeHouse::DIS->value => true,
                KeyforgeHouse::LOGOS->value => true,
                KeyforgeHouse::MARS->value => true,
                KeyforgeHouse::SANCTUM->value => false,
                KeyforgeHouse::REDEMPTION->value => false,
                KeyforgeHouse::SAURIAN->value => false,
                KeyforgeHouse::SHADOWS->value => false,
                KeyforgeHouse::STAR_ALLIANCE->value => false,
                KeyforgeHouse::UNFATHOMABLE->value => false,
                KeyforgeHouse::UNTAMED->value => false,
                KeyforgeHouse::EKWIDON->value => true,
                KeyforgeHouse::GEISTOID->value => true,
                KeyforgeHouse::SKYBORN->value => true,
            ],
            KeyforgeSet::PV->value => [
                KeyforgeHouse::BROBNAR->value => false,
                KeyforgeHouse::DIS->value => true,
                KeyforgeHouse::LOGOS->value => true,
                KeyforgeHouse::MARS->value => false,
                KeyforgeHouse::SANCTUM->value => true,
                KeyforgeHouse::REDEMPTION->value => false,
                KeyforgeHouse::SAURIAN->value => true,
                KeyforgeHouse::SHADOWS->value => true,
                KeyforgeHouse::STAR_ALLIANCE->value => true,
                KeyforgeHouse::UNFATHOMABLE->value => false,
                KeyforgeHouse::UNTAMED->value => true,
                KeyforgeHouse::EKWIDON->value => false,
                KeyforgeHouse::GEISTOID->value => false,
                KeyforgeHouse::SKYBORN->value => false,
            ],
            KeyforgeSet::U22->value => [
                KeyforgeHouse::BROBNAR->value => true,
                KeyforgeHouse::DIS->value => true,
                KeyforgeHouse::LOGOS->value => true,
                KeyforgeHouse::MARS->value => true,
                KeyforgeHouse::SANCTUM->value => true,
                KeyforgeHouse::REDEMPTION->value => false,
                KeyforgeHouse::SAURIAN->value => true,
                KeyforgeHouse::SHADOWS->value => true,
                KeyforgeHouse::STAR_ALLIANCE->value => true,
                KeyforgeHouse::UNFATHOMABLE->value => true,
                KeyforgeHouse::UNTAMED->value => true,
                KeyforgeHouse::EKWIDON->value => true,
                KeyforgeHouse::GEISTOID->value => false,
                KeyforgeHouse::SKYBORN->value => false,
            ],
            KeyforgeSet::VM23->value => [
                KeyforgeHouse::BROBNAR->value => true,
                KeyforgeHouse::DIS->value => true,
                KeyforgeHouse::LOGOS->value => true,
                KeyforgeHouse::MARS->value => true,
                KeyforgeHouse::SANCTUM->value => false,
                KeyforgeHouse::REDEMPTION->value => false,
                KeyforgeHouse::SAURIAN->value => true,
                KeyforgeHouse::SHADOWS->value => false,
                KeyforgeHouse::STAR_ALLIANCE->value => true,
                KeyforgeHouse::UNFATHOMABLE->value => false,
                KeyforgeHouse::UNTAMED->value => true,
                KeyforgeHouse::EKWIDON->value => false,
                KeyforgeHouse::GEISTOID->value => false,
                KeyforgeHouse::SKYBORN->value => false,
            ],
            KeyforgeSet::VM24->value => [
                KeyforgeHouse::BROBNAR->value => true,
                KeyforgeHouse::DIS->value => true,
                KeyforgeHouse::LOGOS->value => false,
                KeyforgeHouse::MARS->value => false,
                KeyforgeHouse::SANCTUM->value => true,
                KeyforgeHouse::REDEMPTION->value => false,
                KeyforgeHouse::SAURIAN->value => false,
                KeyforgeHouse::SHADOWS->value => true,
                KeyforgeHouse::STAR_ALLIANCE->value => true,
                KeyforgeHouse::UNFATHOMABLE->value => true,
                KeyforgeHouse::UNTAMED->value => true,
                KeyforgeHouse::EKWIDON->value => false,
                KeyforgeHouse::GEISTOID->value => false,
                KeyforgeHouse::SKYBORN->value => false,
            ],
            KeyforgeSet::VM25->value => [
                KeyforgeHouse::BROBNAR->value => false,
                KeyforgeHouse::DIS->value => false,
                KeyforgeHouse::LOGOS->value => true,
                KeyforgeHouse::MARS->value => true,
                KeyforgeHouse::SANCTUM->value => false,
                KeyforgeHouse::REDEMPTION->value => false,
                KeyforgeHouse::SAURIAN->value => true,
                KeyforgeHouse::SHADOWS->value => true,
                KeyforgeHouse::STAR_ALLIANCE->value => false,
                KeyforgeHouse::UNFATHOMABLE->value => true,
                KeyforgeHouse::UNTAMED->value => false,
                KeyforgeHouse::EKWIDON->value => true,
                KeyforgeHouse::GEISTOID->value => true,
                KeyforgeHouse::SKYBORN->value => false,
            ],
            KeyforgeSet::MoM->value => [
                KeyforgeHouse::BROBNAR->value => false,
                KeyforgeHouse::DIS->value => true,
                KeyforgeHouse::LOGOS->value => true,
                KeyforgeHouse::MARS->value => false,
                KeyforgeHouse::SANCTUM->value => true,
                KeyforgeHouse::REDEMPTION->value => false,
                KeyforgeHouse::SAURIAN->value => true,
                KeyforgeHouse::SHADOWS->value => true,
                KeyforgeHouse::STAR_ALLIANCE->value => true,
                KeyforgeHouse::UNFATHOMABLE->value => false,
                KeyforgeHouse::UNTAMED->value => true,
                KeyforgeHouse::EKWIDON->value => false,
                KeyforgeHouse::GEISTOID->value => false,
                KeyforgeHouse::SKYBORN->value => false,
            ],
            KeyforgeSet::ToC->value => [
                KeyforgeHouse::BROBNAR->value => false,
                KeyforgeHouse::DIS->value => true,
                KeyforgeHouse::LOGOS->value => true,
                KeyforgeHouse::MARS->value => false,
                KeyforgeHouse::SANCTUM->value => false,
                KeyforgeHouse::REDEMPTION->value => true,
                KeyforgeHouse::SAURIAN->value => false,
                KeyforgeHouse::SHADOWS->value => true,
                KeyforgeHouse::STAR_ALLIANCE->value => false,
                KeyforgeHouse::UNFATHOMABLE->value => false,
                KeyforgeHouse::UNTAMED->value => true,
                KeyforgeHouse::EKWIDON->value => false,
                KeyforgeHouse::GEISTOID->value => true,
                KeyforgeHouse::SKYBORN->value => true,
            ],
            KeyforgeSet::DIS->value => [
                KeyforgeHouse::BROBNAR->value => true,
                KeyforgeHouse::DIS->value => true,
                KeyforgeHouse::LOGOS->value => true,
                KeyforgeHouse::MARS->value => false,
                KeyforgeHouse::SANCTUM->value => true,
                KeyforgeHouse::REDEMPTION->value => false,
                KeyforgeHouse::SAURIAN->value => false,
                KeyforgeHouse::SHADOWS->value => true,
                KeyforgeHouse::STAR_ALLIANCE->value => true,
                KeyforgeHouse::UNFATHOMABLE->value => false,
                KeyforgeHouse::UNTAMED->value => true,
                KeyforgeHouse::EKWIDON->value => false,
                KeyforgeHouse::GEISTOID->value => false,
                KeyforgeHouse::SKYBORN->value => false,
            ],
        ];

        return $this->render('Keyforge/Wiki/wiki.html.twig', ['housesPerSet' => $housesPerSet]);
    }
}
